esphome:
  name: mintymcu_ir
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: "MintyMCU_IR WiFi Signal Sensor"
    update_interval: 60s
  - platform: uptime
    name: "MintyMCU_IR Uptime Sensor"
    update_interval: 60s
    filters:
      - lambda: return x / (24 * 3600);
    unit_of_measumerent: "days"

binary_sensor:
    - platform: status
      name: "MintyMCU_IR Status"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "MintyMCU_IR IP Address"
    ssid:
      name: "MintyMCU_IR Connected SSID"
    bssid:
      name: "MintyMCU_IR Connected BSSID"
  - platform: version
    name: "MintyMCU_IR ESPHome Version"

light:
  - platform: neopixelbus
    type: GRB
    pin: GPIO23
    num_leds: 144
    name: "MintyRGB DeskLight"
    color_correct: [15%, 15%, 15%]